version: '3'

services:
  app:
    # Use the Dockerfile in the current directory to build the image (Dockerfile is in the current directory)
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      # Mount the current directory to the container
      - .:/home/node/app
